Update Send-Many-Interfaces
friedger/stacks-send-many pull request #3
Opened 2021-04-27 18:12 UTC by OmurCataltepe

2021-04-27 18:30 UTC, friedger requested changes

2021-04-27 18:30 UTC, friedger commented on package-lock.json
> +  "name": "stacks-send-many",
we use just yarn, package-lock.json should be removed.

2021-04-27 18:30 UTC, friedger commented on package.json
> +    "yarn": "^1.22.10"
Do we need that?

2021-04-27 18:30 UTC, friedger commented on src/App.js
> +      {!authenticated && <Landing />}
Changes in this file should be reverted

2021-04-27 18:30 UTC, friedger commented on src/components/SendManyInput.js
> +export function SendManyInput({ onKeyUp, key }) {
This is a component that represents just one row.

2021-04-27 18:30 UTC, friedger commented on src/styles/style.css
> +	width: 920px;
Why 920px ?

2021-04-27 18:30 UTC, friedger commented on src/styles/style.css
> +.container-contact100 {
Do we need all these styles? Is bootstrap not enough?

2021-04-28 07:07 UTC, OmurCataltepe commented
Probably I worked on an old version. I think it's better to get the last version and just move the SendManyInput.js and style.css. Because I only changed these files, I don't have any idea about the other files.

2021-04-28 09:22 UTC, closed without merging