Add search params read for send many
friedger/stacks-send-many pull request #34
Opened 2024-05-11 10:34 UTC by hozzjss

This PR should add the feature to fetch the data from the url 
Closes #31

2024-05-12 16:10 UTC, friedger reviewed
Looks good! Just one question before merging.

2024-05-13 15:21 UTC, hozzjss commented on src/components/SendManyInputContainer.tsx
> +  useEffect(() => {
This should run only once when page loads get all the parameters and fill up the rows, there is an improvement that can be made here if the project switches to `react-router-dom` where we'd watch the changes in search and have a bi-directional data flow whereby the changes in search updates the component state and the other way around
However, with the current reach router that im not sure is possible

2024-05-13 15:21 UTC, hozzjss commented on src/components/SendManyInputContainer.tsx
> +      const { amount, recipient, memo } =
Great Idea I'll push something for you to review

2024-05-13 16:56 UTC, friedger commented on src/components/SendManyInputContainer.tsx
> +  useEffect(() => {
The code will run once without using useEffect

2024-05-16 10:57 UTC, friedger requested changes
Looks good. Just the router.tsx file needs a fix.

2024-05-16 10:57 UTC, friedger commented on src/router.tsx
> +const router = createBrowserRouter([
This can be removed or the content of Apps.tsx moved to here.

2024-05-16 11:29 UTC, friedger approved these changes

2024-05-16 11:29 UTC, merged